### ISSUE TITLE
incorporate knowledge from smashingmagazine article on imagemagick

### ISSUE THREAD

**Issue by danielberndt** [danielberndt/gulp-inline-resize#1]
link is here: http://www.smashingmagazine.com/2015/06/25/efficient-image-resizing-with-imagemagick/

**Comment by Metis77** [comment]
just found the image sizes are huge.
Can you give an example on how to optimize the settings in gulp?

**Comment by danielberndt** [comment]
One option would be to add the Imagemin plugin to the output of the resizer:

(redacted snippet from the README)

```
var imgFilter = filter("**/*.+(jpg|png|gif)");

return getAssetStream()
    .pipe(imgFilter)
    .pipe(imagemin({progressive: true}))
    .pipe(imgFilter.restore())
    .pipe(gulp.dest("dist"));
```
