### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by Metis77** [danielberndt/gulp-inline-resize#3]
As of performance i have different tasks.
One for styles, one for templates.

The caching does not work whenever gulp watcher fires a different task.
This is an example gulp file

``` javascript
var gulp            = require("gulp");
var gutil           = require("gulp-util");

var concat          = require('gulp-concat');
var uglify          = require('gulp-uglify');

var sass            = require('gulp-sass');
var sourcemaps      = require('gulp-sourcemaps');
var autoprefixer    = require('gulp-autoprefixer');

var swig            = require('gulp-swig');

var browserSync     = require('browser-sync').create();


var src   = './app/';
var dest  = './public/';


/*
 * generic tasks
 */
gulp.task('default', function() {
    gulp.start('serve');
});
gulp.task('production', function() {
    gulp.start('sass', 'templates', 'js');
});


/**
 *  SASS
 *  https://github.com/sindresorhus/gulp-autoprefixer/issues/8
 */
gulp.task('sass', function () {
    return gulp.src(src + 'styles/main.scss')
        .pipe(sourcemaps.init())
            .pipe(sass(
                {
                    outputStyle: 'compressed'
                }
            ))
        .pipe(sourcemaps.write())
        .pipe(sourcemaps.init({loadMaps: true}))
            .pipe(autoprefixer(
                {
                    browsers: [
                        '> 1%',
                        'last 2 versions',
                        'firefox >= 4',
                        'safari 7',
                        'safari 8',
                        'IE 8',
                        'IE 9',
                        'IE 10',
                        'IE 11'
                    ],
                }
            ))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(dest + 'css/'))
        .pipe(browserSync.stream());
});







/**
 * Templates task - compiles templates.
 */
gulp.task('templates', function() {
    return gulp.src(src+'templates/pages/**/*.swig', { 
            base: src+'templates/pages/' 
        })
        .pipe(swig({
            defaults: { cache: false },
            load_json: true,
            json_path: src+'templates/data/'
        }))
        .pipe(gulp.dest(dest))
        .pipe(browserSync.stream());
});










/**
 * JavaScript - main.js task.
 */
gulp.task('js', function() {
    return gulp.src([
            src+'js/libraries/*.js',
            src+'js/main/*.js',
        ])
        .pipe(concat('main.js'))
        .pipe(uglify())
        .pipe(gulp.dest(dest+'js/'))
        .pipe(browserSync.stream());
});










/**
 *  browserSync
 */

// Static Server + watching scss/html files
gulp.task('serve', ['sass','templates', 'js'], function() {

    browserSync.init({
        server: dest,
        open: false,
        reloadOnRestart: true,
        notify: false,
    });

    gulp.watch(src + 'js/**/*', ['js']);
    gulp.watch(src + 'styles/**/*', ['sass']);
    gulp.watch(src + 'templates/**/*', ['templates']);
});


```

Could `gulp-newer` help here?
https://www.npmjs.com/package/gulp-newer

**Comment by danielberndt** [comment]
What is the issue exactly? Does the cache store things it should not have cached, or does the cache not store enough – leading to a lot of images being resized multiple times?

**Comment by Metis77** [comment]
If run the same single task, images are cached and not recreated.

But if the task changes, alle images are recreated.

in the example above:
run
`templates` images are created the first time
`templates` runs again, images are perfectly cached
`sass` when this task runs, all images used  here are created, even recreated, if they already existed from task templates.
`templates` now all images are recreated. cache of this task got lost.
...

**Comment by danielberndt** [comment]
Okay. Got it. And I already have an idea where to look for the error :)

**Comment by Metis77** [comment]
maybe this issue / suggestion will do the trick too: https://github.com/danielberndt/gulp-inline-resize/issues/4

**Comment by danielberndt** [comment]
Alright. I just fixed this by allowing you to set a global option called `setMaxCacheAge`. See [here](https://github.com/danielberndt/gulp-inline-resize#global-options)

Setting a `MaxCacheAge` of 50 or 100 should be fine, I guess.

**Comment by danielberndt** [comment]
fyi, this issue could have been resolved by restructuring the gulpfile by merging all relevant streams into one and apply `inlineResize()` on the merged stream (as shown in the README).

But I think it's fair to assume that doing so is not to everyone's taste. Therefore I'm fine with introducing the work around posted above :)

**Comment by Metis77** [comment]
Thanks a lot.

> fyi, this issue could have been resolved by restructuring the gulpfile by merging all relevant streams into one and apply inlineResize() on the merged stream (as shown in the README).

I separated the tasks because I did not want all task to be run every time.
In the meanwhile I fond a workaround with `gulp-newer` that makes both possible to.
