### ISSUE TITLE
skip recreation of img

### ISSUE THREAD

**Issue by Metis77** [danielberndt/gulp-inline-resize#4]
if the img to be generated already exists on target, recreation should be omitted.

**Comment by danielberndt** [comment]
That's a tricky one!

Since this plugin is operating with streams, it can't really know for sure what happens to the processed images further down the pipe. They could be renamed, minified, turned into sprites and more! 

I hope that the fix for #3 helps to speed up your workflow enough to make this issue kind of irrelevant, because there's not too much I can do here.

**Comment by Metis77** [comment]
What I intended to solved by this, is that I do not want to recreate all images when I start the task the first time.
At the current project there will be hundrets of images with several SrcSets ... 

I experienced with `gulp-cache`. But it did not work well together with `gulp-inline-resize`.

**Comment by danielberndt** [comment]
Hmm.. maybe it's possible to add an option to `inlineResize` to allow for a "naive" type of caching, i.e assume that the images won't be changed further down the pipe and will not be resized if the target already exists.

**Comment by Metis77** [comment]
> Hmm.. maybe it's possible to add an option to inlineResize to allow for a "naive" type of caching, i.e assume that the images won't be changed further down the pipe and will not be resized if the target already exists.

Yes and especially if I change the files later on, for example optimize them, I want to prevent recreation, as then I would have to optimize them again.
So your idea would help a lot in reducing cpu time.

**Comment by danielberndt** [comment]
just published v0.1.5 containing an option called `naiveCache`. Check the README for the usage and let me know if it works for you!

**Comment by Metis77** [comment]
this is awesome
